package cadenafarmacias_tbd1;

import javax.swing.JOptionPane;


public class CadenaFarmacias_TBD1 extends javax.swing.JFrame {
    ConexionDB conectar;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CadenaFarmacias_TBD1.class.getName());

    public CadenaFarmacias_TBD1() {
        initComponents();
        this.setTitle("Sistema de Control e Inventarios");
        TurnoPanel.setVisible(false);
        verReportesPanel.setVisible(false);
        iniciarTurnoPanel.setVisible(false);
        setLocationRelativeTo(null);
        
//        conectar = new ConexionDB();
//        conectar.getConnection();
//        conectar.insertar("David Castro", "david@gmail.com", "3344-2934");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        pantallaPanel = new javax.swing.JPanel();
        bienvenidoLabel = new javax.swing.JLabel();
        imagenInicioLabel = new javax.swing.JLabel();
        reportesButton = new javax.swing.JButton();
        iniciarTurnoButton = new javax.swing.JButton();
        seleccionInicioLabel = new javax.swing.JLabel();
        verReportesPanel = new javax.swing.JPanel();
        ReportesTabbedPane = new javax.swing.JTabbedPane();
        VentasPanel = new javax.swing.JPanel();
        precioVigentesPanel = new javax.swing.JPanel();
        topProductosPanel = new javax.swing.JPanel();
        inventarioEstimadoPanel = new javax.swing.JPanel();
        cierreTurnoPanel = new javax.swing.JPanel();
        entregasPendientesPanel = new javax.swing.JPanel();
        MargenProductoPanel = new javax.swing.JPanel();
        RankingFarmaciasPanel = new javax.swing.JPanel();
        volverDeReportesButton = new javax.swing.JButton();
        TurnoPanel = new javax.swing.JPanel();
        TurnoTabbedPane = new javax.swing.JTabbedPane();
        paginaInicioTurnoPanel = new javax.swing.JPanel();
        bienvenidoTurnoLabel = new javax.swing.JLabel();
        finalizarTurnoButton = new javax.swing.JButton();
        registrarVentaPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        buscarProductoLabel = new javax.swing.JLabel();
        ingresarProductoTextField = new javax.swing.JTextField();
        buscarProductoButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        productosIngresarTable = new javax.swing.JTable();
        agregarProductoButton = new javax.swing.JButton();
        registrarRecepciónPanel = new javax.swing.JPanel();
        preciosVigentesPanel = new javax.swing.JPanel();
        registrarInventarioFisicoPanel = new javax.swing.JPanel();
        iniciarTurnoPanel = new javax.swing.JPanel();
        ingresarIdClienteLabel = new javax.swing.JLabel();
        idClienteTextField = new javax.swing.JTextField();
        iniciarTButton = new javax.swing.JButton();
        ingresarIdFarmaciaLabel = new javax.swing.JLabel();
        idFarmaciaTextField = new javax.swing.JTextField();

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pantallaPanel.setBackground(new java.awt.Color(153, 153, 255));

        bienvenidoLabel.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        bienvenidoLabel.setForeground(new java.awt.Color(0, 0, 0));
        bienvenidoLabel.setText("¡¡BIENVENIDO!!");

        imagenInicioLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cadenafarmacias_tbd1/images/imagen inicio.jpg"))); // NOI18N
        imagenInicioLabel.setText("jLabel1");

        reportesButton.setBackground(new java.awt.Color(0, 0, 102));
        reportesButton.setForeground(new java.awt.Color(255, 255, 255));
        reportesButton.setText("Ver Reportes");
        reportesButton.addActionListener(this::reportesButtonActionPerformed);

        iniciarTurnoButton.setBackground(new java.awt.Color(0, 0, 102));
        iniciarTurnoButton.setForeground(new java.awt.Color(255, 255, 255));
        iniciarTurnoButton.setText("Iniciar Turno");
        iniciarTurnoButton.addActionListener(this::iniciarTurnoButtonActionPerformed);

        seleccionInicioLabel.setForeground(new java.awt.Color(0, 0, 0));
        seleccionInicioLabel.setText("Seleccione lo que desea hacer:");

        javax.swing.GroupLayout pantallaPanelLayout = new javax.swing.GroupLayout(pantallaPanel);
        pantallaPanel.setLayout(pantallaPanelLayout);
        pantallaPanelLayout.setHorizontalGroup(
            pantallaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pantallaPanelLayout.createSequentialGroup()
                .addGap(208, 208, 208)
                .addComponent(reportesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(149, 149, 149)
                .addComponent(iniciarTurnoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pantallaPanelLayout.createSequentialGroup()
                .addGap(0, 161, Short.MAX_VALUE)
                .addGroup(pantallaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pantallaPanelLayout.createSequentialGroup()
                        .addComponent(imagenInicioLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(150, 150, 150))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pantallaPanelLayout.createSequentialGroup()
                        .addComponent(bienvenidoLabel)
                        .addGap(282, 282, 282))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pantallaPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(seleccionInicioLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(363, 363, 363))
        );
        pantallaPanelLayout.setVerticalGroup(
            pantallaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pantallaPanelLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(bienvenidoLabel)
                .addGap(18, 18, 18)
                .addComponent(imagenInicioLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(seleccionInicioLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pantallaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reportesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iniciarTurnoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        verReportesPanel.setBackground(new java.awt.Color(255, 255, 255));

        ReportesTabbedPane.setBackground(new java.awt.Color(255, 255, 255));

        VentasPanel.setBackground(new java.awt.Color(0, 153, 153));

        javax.swing.GroupLayout VentasPanelLayout = new javax.swing.GroupLayout(VentasPanel);
        VentasPanel.setLayout(VentasPanelLayout);
        VentasPanelLayout.setHorizontalGroup(
            VentasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 911, Short.MAX_VALUE)
        );
        VentasPanelLayout.setVerticalGroup(
            VentasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
        );

        ReportesTabbedPane.addTab("Ventas", VentasPanel);

        precioVigentesPanel.setBackground(new java.awt.Color(0, 153, 153));

        javax.swing.GroupLayout precioVigentesPanelLayout = new javax.swing.GroupLayout(precioVigentesPanel);
        precioVigentesPanel.setLayout(precioVigentesPanelLayout);
        precioVigentesPanelLayout.setHorizontalGroup(
            precioVigentesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 911, Short.MAX_VALUE)
        );
        precioVigentesPanelLayout.setVerticalGroup(
            precioVigentesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
        );

        ReportesTabbedPane.addTab("Previos Vigentes", precioVigentesPanel);

        topProductosPanel.setBackground(new java.awt.Color(0, 153, 153));

        javax.swing.GroupLayout topProductosPanelLayout = new javax.swing.GroupLayout(topProductosPanel);
        topProductosPanel.setLayout(topProductosPanelLayout);
        topProductosPanelLayout.setHorizontalGroup(
            topProductosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 911, Short.MAX_VALUE)
        );
        topProductosPanelLayout.setVerticalGroup(
            topProductosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
        );

        ReportesTabbedPane.addTab("Top Productos", topProductosPanel);

        inventarioEstimadoPanel.setBackground(new java.awt.Color(0, 153, 153));

        javax.swing.GroupLayout inventarioEstimadoPanelLayout = new javax.swing.GroupLayout(inventarioEstimadoPanel);
        inventarioEstimadoPanel.setLayout(inventarioEstimadoPanelLayout);
        inventarioEstimadoPanelLayout.setHorizontalGroup(
            inventarioEstimadoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 911, Short.MAX_VALUE)
        );
        inventarioEstimadoPanelLayout.setVerticalGroup(
            inventarioEstimadoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
        );

        ReportesTabbedPane.addTab("Inventario Estimado", inventarioEstimadoPanel);

        cierreTurnoPanel.setBackground(new java.awt.Color(0, 153, 153));

        javax.swing.GroupLayout cierreTurnoPanelLayout = new javax.swing.GroupLayout(cierreTurnoPanel);
        cierreTurnoPanel.setLayout(cierreTurnoPanelLayout);
        cierreTurnoPanelLayout.setHorizontalGroup(
            cierreTurnoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 911, Short.MAX_VALUE)
        );
        cierreTurnoPanelLayout.setVerticalGroup(
            cierreTurnoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
        );

        ReportesTabbedPane.addTab("Cierre de Turno", cierreTurnoPanel);

        entregasPendientesPanel.setBackground(new java.awt.Color(0, 153, 153));

        javax.swing.GroupLayout entregasPendientesPanelLayout = new javax.swing.GroupLayout(entregasPendientesPanel);
        entregasPendientesPanel.setLayout(entregasPendientesPanelLayout);
        entregasPendientesPanelLayout.setHorizontalGroup(
            entregasPendientesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 911, Short.MAX_VALUE)
        );
        entregasPendientesPanelLayout.setVerticalGroup(
            entregasPendientesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
        );

        ReportesTabbedPane.addTab("Entregas Pendientes", entregasPendientesPanel);

        MargenProductoPanel.setBackground(new java.awt.Color(0, 153, 153));

        javax.swing.GroupLayout MargenProductoPanelLayout = new javax.swing.GroupLayout(MargenProductoPanel);
        MargenProductoPanel.setLayout(MargenProductoPanelLayout);
        MargenProductoPanelLayout.setHorizontalGroup(
            MargenProductoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 911, Short.MAX_VALUE)
        );
        MargenProductoPanelLayout.setVerticalGroup(
            MargenProductoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
        );

        ReportesTabbedPane.addTab("Margen Producto", MargenProductoPanel);

        RankingFarmaciasPanel.setBackground(new java.awt.Color(0, 153, 153));

        javax.swing.GroupLayout RankingFarmaciasPanelLayout = new javax.swing.GroupLayout(RankingFarmaciasPanel);
        RankingFarmaciasPanel.setLayout(RankingFarmaciasPanelLayout);
        RankingFarmaciasPanelLayout.setHorizontalGroup(
            RankingFarmaciasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 911, Short.MAX_VALUE)
        );
        RankingFarmaciasPanelLayout.setVerticalGroup(
            RankingFarmaciasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
        );

        ReportesTabbedPane.addTab("Ranking Farmacias", RankingFarmaciasPanel);

        volverDeReportesButton.setBackground(new java.awt.Color(255, 0, 0));
        volverDeReportesButton.setForeground(new java.awt.Color(255, 255, 255));
        volverDeReportesButton.setText("Volver");
        volverDeReportesButton.addActionListener(this::volverDeReportesButtonActionPerformed);

        javax.swing.GroupLayout verReportesPanelLayout = new javax.swing.GroupLayout(verReportesPanel);
        verReportesPanel.setLayout(verReportesPanelLayout);
        verReportesPanelLayout.setHorizontalGroup(
            verReportesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ReportesTabbedPane)
            .addGroup(verReportesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(volverDeReportesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        verReportesPanelLayout.setVerticalGroup(
            verReportesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(verReportesPanelLayout.createSequentialGroup()
                .addComponent(ReportesTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(volverDeReportesButton)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        TurnoPanel.setBackground(new java.awt.Color(255, 255, 255));

        paginaInicioTurnoPanel.setBackground(new java.awt.Color(0, 153, 102));

        bienvenidoTurnoLabel.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        bienvenidoTurnoLabel.setForeground(new java.awt.Color(255, 255, 255));
        bienvenidoTurnoLabel.setText("Bienvenido");

        finalizarTurnoButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        finalizarTurnoButton.setText("Finalizar Turno");
        finalizarTurnoButton.addActionListener(this::finalizarTurnoButtonActionPerformed);

        javax.swing.GroupLayout paginaInicioTurnoPanelLayout = new javax.swing.GroupLayout(paginaInicioTurnoPanel);
        paginaInicioTurnoPanel.setLayout(paginaInicioTurnoPanelLayout);
        paginaInicioTurnoPanelLayout.setHorizontalGroup(
            paginaInicioTurnoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paginaInicioTurnoPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(paginaInicioTurnoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(finalizarTurnoButton)
                    .addComponent(bienvenidoTurnoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(640, Short.MAX_VALUE))
        );
        paginaInicioTurnoPanelLayout.setVerticalGroup(
            paginaInicioTurnoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paginaInicioTurnoPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(bienvenidoTurnoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 375, Short.MAX_VALUE)
                .addComponent(finalizarTurnoButton)
                .addGap(15, 15, 15))
        );

        TurnoTabbedPane.addTab("Página Inicio", paginaInicioTurnoPanel);

        registrarVentaPanel.setBackground(new java.awt.Color(0, 153, 102));

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 893, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 898, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jPanel1);

        buscarProductoLabel.setText("Busque el producto que desea agregar a la venta:");

        buscarProductoButton.setText("Buscar");
        buscarProductoButton.addActionListener(this::buscarProductoButtonActionPerformed);

        productosIngresarTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre de Producto", "Precio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(productosIngresarTable);

        agregarProductoButton.setText("Agregar");
        agregarProductoButton.addActionListener(this::agregarProductoButtonActionPerformed);

        javax.swing.GroupLayout registrarVentaPanelLayout = new javax.swing.GroupLayout(registrarVentaPanel);
        registrarVentaPanel.setLayout(registrarVentaPanelLayout);
        registrarVentaPanelLayout.setHorizontalGroup(
            registrarVentaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registrarVentaPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(registrarVentaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(registrarVentaPanelLayout.createSequentialGroup()
                        .addComponent(buscarProductoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ingresarProductoTextField)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buscarProductoButton)
                        .addGap(28, 28, 28))
                    .addGroup(registrarVentaPanelLayout.createSequentialGroup()
                        .addGroup(registrarVentaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(agregarProductoButton)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 866, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        registrarVentaPanelLayout.setVerticalGroup(
            registrarVentaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registrarVentaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(registrarVentaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ingresarProductoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarProductoLabel)
                    .addComponent(buscarProductoButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(agregarProductoButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE))
        );

        TurnoTabbedPane.addTab("Registrar Venta", registrarVentaPanel);

        registrarRecepciónPanel.setBackground(new java.awt.Color(0, 153, 102));

        javax.swing.GroupLayout registrarRecepciónPanelLayout = new javax.swing.GroupLayout(registrarRecepciónPanel);
        registrarRecepciónPanel.setLayout(registrarRecepciónPanelLayout);
        registrarRecepciónPanelLayout.setHorizontalGroup(
            registrarRecepciónPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 911, Short.MAX_VALUE)
        );
        registrarRecepciónPanelLayout.setVerticalGroup(
            registrarRecepciónPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 525, Short.MAX_VALUE)
        );

        TurnoTabbedPane.addTab("Registrar Recepción", registrarRecepciónPanel);

        preciosVigentesPanel.setBackground(new java.awt.Color(0, 153, 102));

        javax.swing.GroupLayout preciosVigentesPanelLayout = new javax.swing.GroupLayout(preciosVigentesPanel);
        preciosVigentesPanel.setLayout(preciosVigentesPanelLayout);
        preciosVigentesPanelLayout.setHorizontalGroup(
            preciosVigentesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 911, Short.MAX_VALUE)
        );
        preciosVigentesPanelLayout.setVerticalGroup(
            preciosVigentesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 525, Short.MAX_VALUE)
        );

        TurnoTabbedPane.addTab("Precios Vigentes", preciosVigentesPanel);

        registrarInventarioFisicoPanel.setBackground(new java.awt.Color(0, 153, 102));

        javax.swing.GroupLayout registrarInventarioFisicoPanelLayout = new javax.swing.GroupLayout(registrarInventarioFisicoPanel);
        registrarInventarioFisicoPanel.setLayout(registrarInventarioFisicoPanelLayout);
        registrarInventarioFisicoPanelLayout.setHorizontalGroup(
            registrarInventarioFisicoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 911, Short.MAX_VALUE)
        );
        registrarInventarioFisicoPanelLayout.setVerticalGroup(
            registrarInventarioFisicoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 525, Short.MAX_VALUE)
        );

        TurnoTabbedPane.addTab("Registrar Inventario Físico", registrarInventarioFisicoPanel);

        javax.swing.GroupLayout TurnoPanelLayout = new javax.swing.GroupLayout(TurnoPanel);
        TurnoPanel.setLayout(TurnoPanelLayout);
        TurnoPanelLayout.setHorizontalGroup(
            TurnoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TurnoTabbedPane)
        );
        TurnoPanelLayout.setVerticalGroup(
            TurnoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TurnoTabbedPane)
        );

        iniciarTurnoPanel.setBackground(new java.awt.Color(51, 255, 153));

        ingresarIdClienteLabel.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        ingresarIdClienteLabel.setForeground(new java.awt.Color(0, 0, 0));
        ingresarIdClienteLabel.setText("Ingrese ID del empleado responsable:");

        idClienteTextField.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N

        iniciarTButton.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        iniciarTButton.setText("Iniciar");
        iniciarTButton.addActionListener(this::iniciarTButtonActionPerformed);

        ingresarIdFarmaciaLabel.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        ingresarIdFarmaciaLabel.setForeground(new java.awt.Color(0, 0, 0));
        ingresarIdFarmaciaLabel.setText("Ingrese ID de Farmacia:");

        idFarmaciaTextField.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N

        javax.swing.GroupLayout iniciarTurnoPanelLayout = new javax.swing.GroupLayout(iniciarTurnoPanel);
        iniciarTurnoPanel.setLayout(iniciarTurnoPanelLayout);
        iniciarTurnoPanelLayout.setHorizontalGroup(
            iniciarTurnoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, iniciarTurnoPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(iniciarTurnoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(idClienteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ingresarIdClienteLabel)
                    .addComponent(iniciarTButton, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ingresarIdFarmaciaLabel)
                    .addComponent(idFarmaciaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(178, 178, 178))
        );
        iniciarTurnoPanelLayout.setVerticalGroup(
            iniciarTurnoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(iniciarTurnoPanelLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(ingresarIdClienteLabel)
                .addGap(18, 18, 18)
                .addComponent(idClienteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(ingresarIdFarmaciaLabel)
                .addGap(18, 18, 18)
                .addComponent(idFarmaciaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(iniciarTButton)
                .addContainerGap(88, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pantallaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(verReportesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(TurnoPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(iniciarTurnoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pantallaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(verReportesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(TurnoPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(iniciarTurnoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void reportesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportesButtonActionPerformed
        pantallaPanel.setVisible(false);
        verReportesPanel.setVisible(true);
    }//GEN-LAST:event_reportesButtonActionPerformed

    private void volverDeReportesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverDeReportesButtonActionPerformed
        pantallaPanel.setVisible(true);
        verReportesPanel.setVisible(false);
    }//GEN-LAST:event_volverDeReportesButtonActionPerformed

    private void iniciarTurnoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarTurnoButtonActionPerformed
        pantallaPanel.setVisible(false);
        iniciarTurnoPanel.setVisible(true);
    }//GEN-LAST:event_iniciarTurnoButtonActionPerformed

    private void buscarProductoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarProductoButtonActionPerformed
        if(ingresarProductoTextField.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "No ha ingresado nombre de producto");
            return;
        }
        
//        conectar.buscarPorducto(ingresarProductoTextField.getText());
    }//GEN-LAST:event_buscarProductoButtonActionPerformed

    private void agregarProductoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarProductoButtonActionPerformed
        
    }//GEN-LAST:event_agregarProductoButtonActionPerformed

    private void iniciarTButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarTButtonActionPerformed
        iniciarTurnoPanel.setVisible(false);
        TurnoPanel.setVisible(true);
    }//GEN-LAST:event_iniciarTButtonActionPerformed

    private void finalizarTurnoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finalizarTurnoButtonActionPerformed
        TurnoPanel.setVisible(false);
        pantallaPanel.setVisible(true);
    }//GEN-LAST:event_finalizarTurnoButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CadenaFarmacias_TBD1().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MargenProductoPanel;
    private javax.swing.JPanel RankingFarmaciasPanel;
    private javax.swing.JTabbedPane ReportesTabbedPane;
    private javax.swing.JPanel TurnoPanel;
    private javax.swing.JTabbedPane TurnoTabbedPane;
    private javax.swing.JPanel VentasPanel;
    private javax.swing.JButton agregarProductoButton;
    private javax.swing.JLabel bienvenidoLabel;
    private javax.swing.JLabel bienvenidoTurnoLabel;
    private javax.swing.JButton buscarProductoButton;
    private javax.swing.JLabel buscarProductoLabel;
    private javax.swing.JPanel cierreTurnoPanel;
    private javax.swing.JPanel entregasPendientesPanel;
    private javax.swing.JButton finalizarTurnoButton;
    private javax.swing.JTextField idClienteTextField;
    private javax.swing.JTextField idFarmaciaTextField;
    private javax.swing.JLabel imagenInicioLabel;
    private javax.swing.JLabel ingresarIdClienteLabel;
    private javax.swing.JLabel ingresarIdFarmaciaLabel;
    private javax.swing.JTextField ingresarProductoTextField;
    private javax.swing.JButton iniciarTButton;
    private javax.swing.JButton iniciarTurnoButton;
    private javax.swing.JPanel iniciarTurnoPanel;
    private javax.swing.JPanel inventarioEstimadoPanel;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel paginaInicioTurnoPanel;
    private javax.swing.JPanel pantallaPanel;
    private javax.swing.JPanel precioVigentesPanel;
    private javax.swing.JPanel preciosVigentesPanel;
    private javax.swing.JTable productosIngresarTable;
    private javax.swing.JPanel registrarInventarioFisicoPanel;
    private javax.swing.JPanel registrarRecepciónPanel;
    private javax.swing.JPanel registrarVentaPanel;
    private javax.swing.JButton reportesButton;
    private javax.swing.JLabel seleccionInicioLabel;
    private javax.swing.JPanel topProductosPanel;
    private javax.swing.JPanel verReportesPanel;
    private javax.swing.JButton volverDeReportesButton;
    // End of variables declaration//GEN-END:variables
}
